### ISSUE TITLE
Save checksums on disk for next start possible?

### ISSUE THREAD

**Issue by sheggy012** [tbenz9/siasync#4]
Hey, it's me again. 
Could you adapt the tool so that it saves the checksums and continues at the next start? I try to keep a 1TB folder synchronous. But every time I start the tool I have to wait for days until the checksums are formed, at the next PC restart the whole process starts all over again.

**Comment by tbenz9** [comment]
I'm not crazy about storing the checksums on disk, but we just added a feature that will compare filenames, and file-sizes instead of checksuming each file.  If the filename and file-size is identical it considers it the same file, no checksums are performed.  Would that be an acceptable solution to your use case?

**Comment by sheggy012** [comment]
That's even better. Thank you very much for the great work.

**Comment by tbenz9** [comment]
I haven't created an official release yet, but you're welcome to build from source to get the new features today.  Or I'd be happy to send you over a Binary to test with if you'd prefer that.
